import streamlit as st

CARDS = [
    {
        "front": "What is phishing?",
        "back": "Digital trickery where criminals pretend to be trusted entities (banks, YouTube, M-PESA) to steal your passwords, money, or personal data.",
        "category": "Basics",
    },
    {
        "front": "What is smishing?",
        "back": "Phishing via SMS/text messages. Fake KRA tax refunds, M-PESA account suspensions, and parcel delivery alerts are common smishing attacks.",
        "category": "Basics",
    },
    {
        "front": "Name 3 red flags in a phishing email",
        "back": "① Urgent or threatening language ('Your account will be closed in 24 hours!')\n② Misspelled sender address (youtube@verify-acc.com)\n③ Generic greeting ('Dear Customer' instead of your name)",
        "category": "Red Flags",
    },
    {
        "front": "What is a fake website?",
        "back": "A pixel-perfect copy of a real login page (e.g. TikTok, Equity Bank) hosted on a fraudulent domain. Anything you type is sent directly to the attacker.",
        "category": "Tactics",
    },
    {
        "front": "How do you check a link safely?",
        "back": "On desktop: hover over the link and read the URL in the status bar without clicking.\nOn mobile: press and hold the link to preview the destination URL.\nAlways look for the real domain before the first '/'.",
        "category": "Safe Habits",
    },
    {
        "front": "What is Two-Factor Authentication (2FA)?",
        "back": "A second layer of security beyond your password — typically a one-time code sent via SMS or generated by an app (Google Authenticator). Even if your password is stolen, 2FA blocks attackers.",
        "category": "Defence",
    },
    {
        "front": "What should you do if you clicked a phishing link?",
        "back": "① Disconnect from the internet immediately\n② Change your passwords on a safe device\n③ Enable 2FA on all important accounts\n④ Scan your device for malware\n⑤ Report to your bank if financial info was shared",
        "category": "Response",
    },
    {
        "front": "Why do scammers target content creators?",
        "back": "Creators have monetised accounts worth real money, large audiences who trust them (perfect for spreading scams), and regularly receive brand-deal requests — making fake sponsorship offers highly believable.",
        "category": "Targets",
    },
    {
        "front": "What is vishing?",
        "back": "Voice phishing — fraudulent phone calls where someone pretends to be your bank, Safaricom support, or a government agency. They create urgency to make you act without thinking.",
        "category": "Tactics",
    },
    {
        "front": "Name 3 safe digital habits",
        "back": "① Always verify the sender before acting on any request\n② Never share an OTP (one-time password) with anyone, ever\n③ Type website URLs directly into the browser instead of clicking links in messages",
        "category": "Safe Habits",
    },
]

CATEGORY_COLORS = {
    "Basics":      "#1e40af",
    "Red Flags":   "#991b1b",
    "Tactics":     "#92400e",
    "Safe Habits": "#065f46",
    "Defence":     "#4c1d95",
    "Response":    "#0c4a6e",
    "Targets":     "#7c2d12",
}

# ── State init ────────────────────────────────────────────────────────────────
if "card_index" not in st.session_state:
    st.session_state.card_index = 0
if "card_flipped" not in st.session_state:
    st.session_state.card_flipped = False

st.title("🃏 Phishing Awareness Flashcards")
st.markdown("Learn the key concepts before entering the lab. Click **Flip** to reveal the answer, then mark cards as learned.")
st.divider()

idx = st.session_state.card_index
card = CARDS[idx]
learned = st.session_state.flashcards_learned
flipped = st.session_state.card_flipped
is_learned = idx in learned

# ── Overall progress ──────────────────────────────────────────────────────────
n_learned = len(learned)
st.progress(n_learned / 10, text=f"**{n_learned}/10 cards learned**")
st.caption(f"Card {idx + 1} of {len(CARDS)} · Category: **{card['category']}**")

# ── Flashcard HTML ────────────────────────────────────────────────────────────
# Front (question): mid-teal surface. Back (answer): dark-teal surface.
bg_color     = "#013140" if flipped else "#026281"
border_color = "#CC9F66" if is_learned else ("rgba(204,159,102,0.5)" if flipped else "rgba(204,159,102,0.3)")
label        = "📖 ANSWER" if flipped else "❓ QUESTION"
text         = card["back"] if flipped else card["front"]
text_html    = text.replace("\n", "<br>")
learned_banner = '<div style="margin-top:14px;color:#CC9F66;font-weight:700;font-size:0.9em;letter-spacing:1px;">✅ LEARNED</div>' if is_learned else ""

st.markdown(f"""
<div style="
    background:{bg_color};
    border:2px solid {border_color};
    border-radius:16px;
    padding:48px 40px;
    text-align:center;
    min-height:200px;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
    margin:8px 0 16px 0;
    box-shadow:0 6px 28px rgba(1,49,64,0.5);
    transition:border-color 0.2s;
">
    <div style="font-size:0.72em;font-weight:700;letter-spacing:3px;color:#CC9F66;margin-bottom:16px;">{label}</div>
    <div style="font-size:1.15em;color:#FFFFFF;line-height:1.75;max-width:580px;">{text_html}</div>
    {learned_banner}
</div>
""", unsafe_allow_html=True)

# ── Action buttons ────────────────────────────────────────────────────────────
b1, b2, b3, b4 = st.columns(4)

with b1:
    if st.button("⬅️ Previous", disabled=(idx == 0), use_container_width=True):
        st.session_state.card_index = idx - 1
        st.session_state.card_flipped = False
        st.rerun()

with b2:
    flip_label = "🔄 Show Question" if flipped else "🔄 Flip Card"
    if st.button(flip_label, use_container_width=True, type="primary"):
        st.session_state.card_flipped = not flipped
        st.rerun()

with b3:
    if is_learned:
        if st.button("↩️ Unmark", use_container_width=True):
            st.session_state.flashcards_learned.discard(idx)
            st.rerun()
    else:
        if st.button("✅ Mark Learned", use_container_width=True):
            st.session_state.flashcards_learned.add(idx)
            st.session_state.card_flipped = False
            st.rerun()

with b4:
    if st.button("Next ➡️", disabled=(idx == len(CARDS) - 1), use_container_width=True):
        st.session_state.card_index = idx + 1
        st.session_state.card_flipped = False
        st.rerun()

st.divider()

# ── Mini overview grid ────────────────────────────────────────────────────────
with st.expander(f"📋 All Cards Overview ({n_learned}/10 learned)"):
    for i, fc in enumerate(CARDS):
        _icon = "✅" if i in learned else ("▶" if i == idx else "⬜")
        _style = "color:#CC9F66;" if i in learned else ("color:#026281;font-weight:600;" if i == idx else "color:rgba(255,255,255,0.6);")
        st.markdown(
            f'<span style="{_style}">{_icon} **{i+1}.** {fc["front"]}</span>',
            unsafe_allow_html=True,
        )

st.divider()

# ── Proceed to lab ────────────────────────────────────────────────────────────
if n_learned >= 5:
    st.success(f"🎉 Great work! You've learned {n_learned}/10 cards. You can now enter the Phishing Lab.")
    if st.button("🔬 Proceed to Phishing Lab →", type="primary", use_container_width=True):
        st.switch_page("pages/03_lab.py")
else:
    remaining = 5 - n_learned
    st.info(f"📌 Mark at least **5 cards** as learned to unlock the lab. ({remaining} more needed)")
